#!/bin/sh
# Copyright 2001 Alberto Gonzalez Iniesta <agi@agi.as>
# Licensed under the GNU General Public License, version 2.  See the file
# /usr/share/common-licenses/GPL or <http://www.gnu.org/copyleft/gpl.txt>.
#
set -e
test $DEBIAN_SCRIPT_DEBUG && set -v -x

# use debconf
. /usr/share/debconf/confmodule

case "$1" in
  configure)
    # get rid of confiles installed by mistake
    rm -f /etc/network/if-up.d/openvpn.if-up.d || true
    rm -f /etc/network/if-down.d/openvpn.if-down.d || true
    db_get openvpn/create_tun || RET="false"
    if [ "$RET" = "true" ]; then
      [ -e /dev/net ] || mkdir -m 755 /dev/net
      [ -d /dev/net -a ! -e /dev/net/tun ] && mknod /dev/net/tun c 10 200
    fi
    # Do we want to move the old S20 symlinks to S18 ones?
    if [ -n "$2" ] ; then
      # PRNG warning
      show_vuln_keys=""
      if dpkg --compare-versions "$2" ge 2.0.6-2 && dpkg --compare-versions "$2" lt 2.1~rc7-2 ; then
        show_vuln_keys="yes"
      fi

      if [ "$show_vuln_keys" = "yes" ]; then
        db_version 2.0
        db_input critical openvpn/vulnerable_prng || true
        db_go
      fi

    fi
  ;;
esac

if [ -x "/etc/init.d/openvpn" ]; then
	if [ -x /usr/sbin/invoke-rc.d ]; then
	   invoke-rc.d openvpn cond-restart || invoke-rc.d openvpn restart
	else
	   /etc/init.d/openvpn cond-restart || /etc/init.d/openvpn restart
	fi
fi

db_stop

#DEBHELPER#

exit 0
# vim:set ai et sts=2 sw=2 tw=0:
