name: Build
on:
  pull_request:

permissions:
  id-token: write
  contents: write

jobs:
  test1:
    name: Install commands
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master

      - name: Install openvpn
        run: |
          brew update
          brew install openvpn
          brew upgrade

      - name: Check
        run: |
          brew list openvpn
