name: C/C++ CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: source build vars and download openvpn source
      run: source ~/work/openvpn-windows-xor/openvpn-windows-xor/generic/build.vars && echo ${OPENVPN_VERSION} && echo ${OPENVPN_URL} && mkdir ~/work/openvpn-windows-xor/openvpn-windows-xor/generic/sources && cd ~/work/openvpn-windows-xor/openvpn-windows-xor/generic/sources && wget ${OPENVPN_URL}
    - name: get openvpn build env setup script
      run: cd ~/work/openvpn-windows-xor/ && wget https://raw.githubusercontent.com/OpenVPN/openvpn-vagrant/master/setup-generic-buildsystem.sh && chmod +x ./setup-generic-buildsystem.sh && ls
    - name: run env setup script
      run: cd ~/work/openvpn-windows-xor/ && sudo ./setup-generic-buildsystem.sh -f
#    - name: make file permissions super permissive
#      run: sudo chmod -R 777 openvpn-windows-xor/
#    - name: build without patches first
#      run: cd ~/work/openvpn-windows-xor/openvpn-windows-xor/generic && echo ${OPENVPN_VERSION} && echo ${OPENVPN_URL} && IMAGEROOT=`pwd`/image-win32 CHOST=i686-w64-mingw32 CBUILD=x86_64-pc-linux-gnu ./build
#    - name: remove version compiled without patches
#      run: sudo rm -rf image-*
    - name: extract openvpn sources
      run: cd ~/work/openvpn-windows-xor/openvpn-windows-xor/generic/sources && tar xfz "./openvpn-${OPENVPN_VERSION}.tar.gz"
    - name: copy patches
      run: cp -r ~/work/openvpn-windows-xor/openvpn-windows-xor/tunnelblick-patches/*  "~/work/openvpn-windows-xor/openvpn-windows-xor/generic/sources/openvpn-${OPENVPN_VERSION}"
    - name: apply patches
      run: cd "~/work/openvpn-windows-xor/openvpn-windows-xor/generic/sources/openvpn-${OPENVPN_VERSION}" && git apply 02-tunnelblick-openvpn_xorpatch-a.diff && git apply 03-tunnelblick-openvpn_xorpatch-b.diff && git apply 04-tunnelblick-openvpn_xorpatch-c.diff && git apply 05-tunnelblick-openvpn_xorpatch-d.diff && git apply 06-tunnelblick-openvpn_xorpatch-e.diff
    - name: recompress openvpn sources
      run: cd ~/work/openvpn-windows-xor/openvpn-windows-xor/generic/sources && tar cfz "./openvpn-${OPENVPN_VERSION}.tar.gz" "./openvpn-${OPENVPN_VERSION}" && rm -rf "./openvpn-${OPENVPN_VERSION}"
    - name: build 64bit bin files from patched openvpn source
      run: cd ~/work/openvpn-windows-xor/openvpn-windows-xor/generic/ && IMAGEROOT=`pwd`/image-win64 CHOST=x86_64-w64-mingw32 CBUILD=x86_64-pc-linux-gnu ./build
#    - name: zip compiled files
#      run: cd $HOME/ && zip -r bin.zip ~/work/openvpn-windows-xor/generic/image-win64/openvpn/bin
    - name: Upload artifact - compiled 64bit bin files
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Compiled 64bit bin files
        path: /home/runner/work/openvpn-windows-xor/openvpn-windows-xor/generic/image-win64/openvpn/bin
    - name: build 32bit bin files from patched openvpn source
      run: cd ~/work/openvpn-windows-xor/openvpn-windows-xor/generic/ && IMAGEROOT=`pwd`/image-win32 CHOST=i686-w64-mingw32 CBUILD=x86_64-pc-linux-gnu ./build
    - name: Upload artifact - compiled 32bit bin files
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Compiled 32bit bin files
        path: /home/runner/work/openvpn-windows-xor/openvpn-windows-xor/generic/image-win32/openvpn/bin
    - name: copy patched openvpn sources to windows build dir
      run: cp -r ~/work/openvpn-windows-xor/openvpn-windows-xor/generic/sources ~/work/openvpn-windows-xor/openvpn-windows-xor/windows-nsis/
    - name: build windows installers
      run: cd ~/work/openvpn-windows-xor/openvpn-windows-xor/windows-nsis/ && mkdir output/ && ./build-complete --output-dir=./output
    - name: Upload artifact - Windows Installer file
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Windows Installer file
        path: /home/runner/work/openvpn-windows-xor/openvpn-windows-xor/windows-nsis/output
