name: Populate dependencies

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      with:
        submodules: 'recursive'

    - name: Bootstrap vcpkg
      working-directory: src/vcpkg
      run: ./bootstrap-vcpkg.sh
    - name: vcpkg version
      working-directory: src/vcpkg
      run: ./vcpkg version
    - name: Run vcpkg (openvpn)
      working-directory: src/openvpn/contrib/vcpkg-manifests/windows/
      run: ${{ github.workspace }}/src/vcpkg/vcpkg install --debug --overlay-triplets ${{ github.workspace }}/src/openvpn/contrib/vcpkg-triplets --overlay-ports ${{ github.workspace }}/src/openvpn/contrib/vcpkg-ports --dry-run

  openvpn-gui:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      with:
        submodules: 'recursive'

    - name: Bootstrap vcpkg
      working-directory: src/vcpkg
      run: ./bootstrap-vcpkg.sh
    - name: vcpkg version
      working-directory: src/vcpkg
      run: ./vcpkg version
    - name: Run vcpkg (openvpn-gui)
      working-directory: src/openvpn-gui
      run: ${{ github.workspace }}/src/vcpkg/vcpkg install --debug --dry-run
