name: Renovate
on:
  schedule:
    - cron: '0/30 * * * *'
  workflow_dispatch:
jobs:
  renovate:
    if: github.repository_owner == 'OpenVPN'
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@22e0a16091fc706b04affe6ae53d5e3358ac4023 # v46.1.19
        with:
          configurationFile: .github/renovate-config.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: >-
            ${{ github.repository_owner }}/openvpn-build,
            ${{ github.repository_owner }}/openvpn,
            ${{ github.repository_owner }}/openvpn-gui,
            ${{ github.repository_owner }}/openvpn-tests
